// By zeelrupapara@gmail.com, Lead Developer
package main

import (
	"greenlync-api-gateway/app"
	// docs are generated by Swag CLI, you have to import them.
	_ "greenlync-api-gateway/docs"
)

// @title						GreenLync API Gateway
// @version					1.0
// @description				GreenLync Cannabis API Gateway
// @termsOfService				https://greenlync.com
// @contact.name				API Support
// @contact.email				zeelrupapara@gmail.com
// @license.url				https://greenlync.com
// @license.name				GreenLync
// @host						localhost:8888
// @BasePath					/
// @Schemes					http https
// @securityDefinitions.basic	BasicAuth
// @securityDefinitions.apikey	BearerAuth
// @in							header
// @name						Authorization
// @description				Type "BearerAuth" followed by a space and Access token.
// @name						Authorization
func main() {

	app.Start()
}
