// Package docs provides Swagger documentation for the GreenLync API Gateway
// This package is typically generated by swag CLI
package docs

// TODO: Run `swag init` to generate the actual documentation
// This is a placeholder to resolve import issues

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0",
	Host:        "localhost:8888",
	BasePath:    "/",
	Schemes:     []string{"http", "https"},
	Title:       "GreenLync API Gateway",
	Description: "GreenLync Cannabis API Gateway",
}